name: Setup CML (Continuous Machine Learning)
description: Sets up CML (Continuous Machine Learning) - https://cml.dev.
author: Iterative, Inc.
inputs:
  version:
    description: The version of CML to install (e.g. '3.0.0').
    default: latest
    required: false
  sudo:
    description: A flag to disable the use of sudo whilst installing CML.
    default: true
    required: false
  override:
    description:
      Override cml install with a git url (e.g. 'npm install
      git://github.com:iterative/cml.git#6a387a23650f20fd5eb81bc0f63a9bfc6f98882e')
    required: false

runs:
  using: node12
  main: dist/index.js
branding:
  icon: terminal
  color: purple
