name: Check CML GitHub Action
on:
  schedule:
    - cron: 0 0 * * *
  pull_request:
  workflow_dispatch:
jobs:
  check:
    strategy:
      matrix:
        system:
          - ubuntu-latest
    runs-on: ${{ matrix.system }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run lint
      - run: npm run test
      - name: local action with '0.3.0'
        uses: ./
        with:
          version: '0.3.0'
      - name: test CML specific version
        run: |
          CML_VER="$(cml-publish --version)"
          if [ "$CML_VER" != '0.3.0' ]; then
            echo $CML_VER
            exit 1
          fi
      - name: local action with git url
        uses: ./
        with:
          version: 'git://github.com:iterative/cml.git#6a387a23650f20fd5eb81bc0f63a9bfc6f98882e'
      - name: test CML specific version
        if: matrix.system != 'windows-latest'
        run: |
          CML_VER="$(cml-publish --version)"
          if [ "$CML_VER" != '0.8.1' ]; then
            echo $CML_VER
            exit 1
          fi
      - name: local action with defaults
        uses: ./
      - name: test CML latest version
        run: |
          CML_VER="$(cml-publish --version)"
          if [ "$CML_VER" == '0.8.1' ]; then
            echo $CML_VER
            exit 1
          fi
      - name: test CML
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo 'Hello CML from ${{ matrix.system }}!' > report.md

          vl2svg assets/vega-lite.json | cml-publish --md >> report.md
          vl2png assets/vega-lite.json | cml-publish --md >> report.md

          cml-send-comment report.md
          cml-send-github-check report.md
